"""empty message

Revision ID: 1fabe649fd68
Revises: None
Create Date: 2016-09-13 18:33:58.402000

"""

# revision identifiers, used by Alembic.
revision = '1fabe649fd68'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('duration', sa.Interval(), nullable=True))
    op.add_column('goals', sa.Column('weight', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'weight')
    op.drop_column('goals', 'duration')
    ### end Alembic commands ###
