"""empty message

Revision ID: 3769a9e7a819
Revises: 1fabe649fd68
Create Date: 2016-09-13 20:08:19.044000

"""

# revision identifiers, used by Alembic.
revision = '3769a9e7a819'
down_revision = '1fabe649fd68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('show', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'show')
    ### end Alembic commands ###
