"""empty message

Revision ID: 587ffd9fc524
Revises: None
Create Date: 2016-08-23 23:04:56.103000

"""

# revision identifiers, used by Alembic.
revision = '587ffd9fc524'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chartType', sa.String(length=40), nullable=True),
    sa.Column('activityName', sa.String(length=50), nullable=True),
    sa.Column('activityType', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charts')
    ### end Alembic commands ###
