"""empty message

Revision ID: 6b9b9f3b7958
Revises: 77884763b2ee
Create Date: 2016-08-27 21:17:15.796000

"""

# revision identifiers, used by Alembic.
revision = '6b9b9f3b7958'
down_revision = '77884763b2ee'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charts', sa.Column('activityNames', postgresql.ARRAY(String(length=70)), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charts', 'activityNames')
    ### end Alembic commands ###
