"""empty message

Revision ID: 77884763b2ee
Revises: 77b037c39fda
Create Date: 2016-08-24 16:02:32.144000

"""

# revision identifiers, used by Alembic.
revision = '77884763b2ee'
down_revision = '77b037c39fda'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charts', sa.Column('display', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charts', 'display')
    ### end Alembic commands ###
