"""empty message

Revision ID: 77b037c39fda
Revises: d9b91ce43fc4
Create Date: 2016-08-24 10:38:31.164000

"""

# revision identifiers, used by Alembic.
revision = '77b037c39fda'
down_revision = 'd9b91ce43fc4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lifts', sa.Column('completed_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lifts', 'completed_time')
    ### end Alembic commands ###
