"""empty message

Revision ID: af00b517aa70
Revises: 3769a9e7a819
Create Date: 2016-09-18 12:32:48.603000

"""

# revision identifiers, used by Alembic.
revision = 'af00b517aa70'
down_revision = '3769a9e7a819'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cardios', sa.Column('user_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cardios', 'user_id')
    ### end Alembic commands ###
