"""empty message

Revision ID: d9b91ce43fc4
Revises: 587ffd9fc524
Create Date: 2016-08-24 00:24:52.734000

"""

# revision identifiers, used by Alembic.
revision = 'd9b91ce43fc4'
down_revision = '587ffd9fc524'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lifts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lifts', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lifts', type_='foreignkey')
    op.drop_column('lifts', 'user_id')
    ### end Alembic commands ###
